# Generated by Django 4.2.8 on 2023-12-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')])),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Finished'), (2, 'Created'), (3, 'Running')], default=2
                    ),
                ),
                ('clients', models.ManyToManyField(to='mailing.client')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Success'), (1, 'Failed')])),
                ('server_response', models.TextField(blank=True, null=True)),
                (
                    'mailing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailing'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='mailing', to='mailing.message'
            ),
        ),
        migrations.AddConstraint(
            model_name='mailinglog',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('server_response__isnull', False), ('status', 1)),
                    models.Q(('status', 1), _negated=True),
                    _connector='OR',
                ),
                name='mailing_mailinglog_not_empty_response_on_failure',
            ),
        ),
    ]
