version: "3.8"

services:

  redis:
    image: redis:6.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 3s
      retries: 10
